apiVersion: v1
kind: Service
metadata:
  name: sgl-scheduler
  namespace: default
spec:
  selector:
    app: sgl-scheduler
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer
