apiVersion: apps/v1
kind: Deployment
metadata:
  name: sgl-middleware
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sgl-middleware
  template:
    metadata:
      labels:
        app: sgl-middleware
    spec:
      serviceAccountName: sgl-middleware-sa
      containers:
      - name: middleware
        image: ghcr.io/zhengkezhou1/sgl-jax-action/middleware:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
