apiVersion: v1
kind: Service
metadata:
  name: "sgl-svc-{{.UserName}}"
  labels:
    app: sgl-tpu
    developer: "{{.UserName}}"
spec:
  selector:
    app: sgl-tpu
    developer: "{{.UserName}}"
  type: LoadBalancer
  ports:
  - name: ssh
    port: 22
    targetPort: 22
    protocol: TCP
